### ISSUE TITLE
Реализовать логику игры бота

### ISSUE THREAD

**Issue by bondiano** [MemeBattle/monorepo#172]
Стратегия игры бота:
1. Если можно положить карточку из открытых (row) на стол кладем, открываем новую (row) карту
2. Если можно положить открытую карту из стека, то кладем, открываем новую карту стека
3. Если нельзя положить карты, то открываем новые карты из стека, если можно, то [2], иначе [4]
4. Пока нельзя положить карту, повторяем [1]

**Comment by MaxAkkerman** [comment]
еще актуальные задачи? все +- 2022 года таски

**Comment by bondiano** [comment]
да, большенство задач актуальная, конкретно эта сделана в отдельном приложении https://github.com/MemeBattle/ligretto-bot-clj

@MaxAkkerman можете брать любую с тегом `good-first-issue`
