### ISSUE TITLE
Create quote component

### ISSUE THREAD

**Issue by Themezv** [MemeBattle/monorepo#200]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/12786682/195127588-e5eda063-b241-4d3a-8a36-bad289fe26f9.png">

Figma: https://www.figma.com/file/jsSsetyPx0r5ams0nir2CP/Untitled?node-id=0%3A1

**Comment by error707-persona** [comment]
I would like to work on it please assign it to me

**Comment by SrigiriSruthi** [comment]
@Themezv can u assign this to me?
