### ISSUE TITLE
Change theme colors

### ISSUE THREAD

**Issue by Themezv** [MemeBattle/monorepo#203]
Colors should be as per design - https://www.figma.com/file/zLXO12ISnORKAut0uduasj/Ligretto?node-id=829%3A535

1. Compare theme colors with design
2. Change colors in ligretto theme palette
3. Change background color in ligretto index.html

**Comment by RachitGarg-12** [comment]
@Themezv i would like to contribute on this issue.

**Comment by Themezv** [comment]
> @Themezv i would like to contribute on this issue.

That will be cool!

**Comment by SrigiriSruthi** [comment]
@Themezv can u assign this to me? iam interested to contribute.

**Comment by Themezv** [comment]
@oximon @bitternectar is issue actual ?

**Comment by oximon** [comment]
There are some problems in Auth app with colours. It should be fixed
