### ISSUE TITLE
SignUp form errors

### ISSUE THREAD

**Issue by Themezv** [MemeBattle/monorepo#226]
# First:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/12786682/196798503-5fc8e198-622a-4f4e-8ce3-c291802412b4.png">

**Steps for reproduce**
1. Enter one letter username and correct email
2. Click signup button

**Expected:**
Error showed only for username

**Actual:**
Email and username in error state

# Second:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/12786682/196799913-c58afbf3-1b1c-434b-8263-23ce2760f444.png">

**Steps for reproduce**
1. Enter exist username
2. Click signup button

**Expected:**
Error text: User with a same username or email already exists
Error showed like on sign in page under fields
<img width="387" alt="image" src="https://user-images.githubusercontent.com/12786682/196800422-ffbe0e19-a718-40dd-ae09-0fc8c7fd2c7a.png">

**Actual:**
Error text: User with a same username or password exists
Error showed for fields

**Comment by Guryanov-Maksim** [comment]
Здравствуйте! Этой проблемой занимаются в данный момент? Если нет, то я могу заняться.

**Comment by Themezv** [comment]
Переасайнил. По описанию не понимаю, что надо сделать в задаче. Давай обсудим)

**Comment by Guryanov-Maksim** [comment]
Спасибо, буду делать.

**Comment by Guryanov-Maksim** [comment]
Еще вопрос. В [руководстве по циклу разработки](https://github.com/MemeBattle/monorepo/blob/master/docs/development-lifecycle.md) сказано, что нужно двигать карточки на [доске](https://github.com/orgs/MemeBattle/projects/1), но у меня они не двигаются. Мне нужно что-то делать с доской?
