### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by Themezv** [MemeBattle/monorepo#326]

**Comment by Guryanov-Maksim** [comment]
**Предлашаемое решение**

RSS-лента будет построена по спецификации RSS 2.0

## API
```
GET /rss/:{lang}
```
`lang = 'ru' | 'en' ;`

**Примерный ответ** с одним постом [what-is-memebattle.en](https://github.com/MemeBattle/monorepo/blob/master/apps/blog/content/posts/what-is-memebattle.en.mdx), тут главное определиться с содержанием rss:

Информация о посте и канале:
```
const channelMetadata = {
    title: 'MemeBattle blog',
    description: 'Technical articles, posts and notes. MemeBattle news',
    link: '{blogHost}/:{lang}/posts',
}

const postMetadata = {
    title: 'What is MemeBattle?',
    publishedAt: '2023-05-28',
    summary: "Post about MemeBattle. How it's started and what is MemeBattle today",
    image: '/content-images/what-is-memebattle/memeBattle-logo.svg',
    author: 'themezv',
    slug: 'what-is-memebattle',
}
```
Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
    <channel>
        <title>{channelMetadata.title}</title>
        <description>{channelMetadata.description}</description>
        <link>{channelMetadata.link}</link>
        <item>
            <title>{postMetadata.title}</title>
            <description>{postMetadata.summary}</description>
            <link>{blogHost}/:{lang}/posts/:{postMetadata.slug}</link>
            <pubDate>{postMetadata.publishedAt in RFC 822 format}</pubDate>
            <author>{postMetadata.author}</author>
            <image>
               <url>{full link to postMetadata.image}</url>
               <title>{image title}</title>
               <link>{The URL to which the image should be linked. This is usually the same as the channel/link. Now that I don't have full understanding of this one. Research is needed}</link>
           </image>
        </item>
    </channel>
</rss>
```

## Общее решение:
1. RSS будет формироваться "на лету" при каждом запросе. Как обсуждалось в телеге 
> если бы мы вдруг переехали с файлов статей на бэкенд со статьями, не пришлось бы ничего переделывать

2. Использовать json-файлы, которые генерирует `contentlayer`,  для получения информации о постах. Как пример, эту функциональность спрятать за отдельной функцией. По мере решения выберу, как это абстрагировать, чтобы также не быть завязанным на способе получения информации о постах (чтение файлов, запрос на отдельный бэкенд-сервис или еще что-то)

## Дополнительная функциональность 
Нужно подтвердить, необходимо ли ее внедрять.
1. Можно подумать над кэшированием сгенерированных rss, если новых постов не создано, чтобы исключить ненужные вычисления.
2. Нужно ли ограничить количество постов в rss (например, 20 самых новых постов)

**Comment by Themezv** [comment]
Список постов можно брать по аналогии с https://github.com/MemeBattle/monorepo/blob/6fedc59ea620e104ed13abd743dbf4da3ec4f0f2/apps/blog/src/app/%5Blocale%5D/posts/_content/index.ts#L2C1-L2C54

**Comment by Guryanov-Maksim** [comment]
> Что об этом говорит стандарт? Я не очень понимаю, как это должно работать.

[Спецификация RSS 2.0](https://www.rssboard.org/rss-2-0-1#hrelementsOfLtitemgt) не устанавливает никаких ограничений на количесво постов: 
> A channel may contain any number of items. 

В интернете ходят разные рекомендации в зависимости от версии стандарта (например, на стэковерфлоу от 15 до 100 попадалось). Они звучат как "Используй столько-то постов". 

Некоторые сервисы, которые могут потреблять фиды, накладывают ограничение на размер фида и количество постов Например:
- **Google News**: Size limit: 1 MB per article and 2 MB per feed. Up to 60 new articles per fetch
- **Google Podcast**: Google Podcasts has an episode count limit, based on the published RSS file size. You should expect a maximum of about 400-700 of the most recent episodes to be available from the published feed, sorted by the <pubDate> value.
- **Yandex Turbo Page**: RSS feed size - 10Mb, Number of item elements - 10000

Пока постов немного неактуально конечно, но размер наверное играет значение. Чтобы фиды быстро доставлялись клиенту.

**Comment by Guryanov-Maksim** [comment]
**Обнoвленное решение с учетом замечаний**
Лента будет построена по стандарту [RFC 4287](https://www.ietf.org/rfc/rfc4287.txt) (используется формат Atom)

## API
```
GET /rss/:{lang}
```
Доступные локали `lang = 'ru' | 'en' `.

**Примерный ответ** с одним постом [what-is-memebattle.en](https://github.com/MemeBattle/monorepo/blob/master/apps/blog/content/posts/what-is-memebattle.en.mdx):
Метаинформация о посте и канале, которая получена из файлов с постами:
```
const channelMetadata = {
    title: 'MemeBattle blog',
    description: 'Technical articles, posts and notes. MemeBattle news',
    link: '{blogHost}/:{lang}/posts',
}

const postMetadata = {
    title: 'What is MemeBattle?',
    publishedAt: '2023-05-28',
    summary: "Post about MemeBattle. How it's started and what is MemeBattle today",
    image: '/content-images/what-is-memebattle/memeBattle-logo.svg',
    author: 'themezv',
    slug: 'what-is-memebattle',
    content: '${post_content_html}'
}
```
Response (тут главное определиться с содержанием rss, нужно ли что-то добавить или убрать):
```
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-US">
     <title>{channelMetadata.title}</title>
     <subtitle>{channelMetadata.description}</subtitle>
     <link type="application/atom+xml" href="{channelMetadata.link}" rel="self" />
     <id>{channelMetadata.link}</id>
     <updated>{Date of the most recent changed/added post in YYYY-MM-DDThh:mmTZD format}</updated>

     <entry>
         <title>{postMetadata.title}</title>
         <link rel="alternate" type="text/html" href="{blogHost}/:{lang}/posts/:{postMetadata.slug}" />
         <id>{blogHost}/:{lang}/posts/:{postMetadata.slug}</id>
         <published>{post publish date in YYYY-MM-DDThh:mmTZD format}</published>
         <updated>{post update date in YYYY-MM-DDThh:mmTZD format }</updated>
         <summary>{postMetadata.summary}</summary>
         <content type="html">{postMetadata.content}</content>
         <author>
            <name>{postMetadata.author}</name>
         </author>
     </entry>
</feed>
```
## Общее решение:
1. По запросу клиента извлечь информацию о канале и постах. Для этих целей использовать json-файлы, которые генерирует `contentlayer`. Как пример, эту функциональность спрятать за отдельной функцией. По мере решения выберу, как это абстрагировать, чтобы также не быть завязанным на способе получения информации о постах (посредством чтения файлов, запроса на отдельный бэкенд-сервис или еще что-то)
2. Из информации, полученной в пункте 1, сформировать ленту в формате Atom. Также думаю сделать отдельной функцией. Формироваться лента будет "на лету" при каждом запросе. Как обсуждалось в телеге, это делается для того, чтобы
> если бы мы вдруг переехали с файлов статей на бэкенд со статьями, не пришлось бы ничего переделывать
3. Отдать сгенерированный ленту клиенту.

## Дополнительная функциональность
Нужно подтвердить, необходимо ли ее внедрять.

1. Нужно ли ограничить количество постов в ленте (например, 20 самых новых постов)
