### ISSUE TITLE
Register page isn't available

### ISSUE THREAD

**Issue by Guryanov-Maksim** [MemeBattle/monorepo#335]
Здравствуйте! Когда перехожу по ссылке [Don't have an account? Sign up](https://ligretto.app/register) со страницы https://ligretto.app/auth/login, то страница регистрации не отображается. Мне кажется, что дело в путях. Если переходить по ссылке https://ligretto.app/auth/register, то страница регистрации доступна.

**Comment by Themezv** [comment]
Здравствуйте! Да, действительно. Есть желание исправить?)

**Comment by Guryanov-Maksim** [comment]
Да, вполне могу попробовать)
