### ISSUE TITLE
Ligretto empty rooms placeholder

### ISSUE THREAD

**Issue by Themezv** [MemeBattle/monorepo#344]
Figma: https://www.figma.com/file/zLXO12ISnORKAut0uduasj/Ligretto?node-id=1481-407&t=zhQE399TNO19cXJY-4

1. Export cat as svg image from figma
2. Optimize svg (e.x. https://jakearchibald.github.io/svgomg/)
3. Show cat as empty placeholder in rooms list

**Comment by ilya-rodin** [comment]
Возьму в работу
