### ISSUE TITLE
Existent user is not found when logging in

### ISSUE THREAD

**Issue by Guryanov-Maksim** [MemeBattle/monorepo#347]
Здравствуйте! Когда пытаешься залогиниться с неправильным паролем, то возникает сообщение "User not found. Check login/email and password" и ошибка 404. Это все выглядит так, будто пользователь не зарегистрирован. Может стоит перефразировать как-то, вроде "Incorrect login/email or password. Please try again", и код ошибки сменить на 401?

**Comment by Themezv** [comment]
Это было сделано в целях безопасности. Чтобы по логину (username/email) нельзя было проверить существование этого пользователя в системе. 
Есть более глобальные планы на CAS - хочется вообще уйти от логинов/паролей и особенно хранения паролей. Поэтому делать что-то не критичное в CAS не хочется

**Comment by Guryanov-Maksim** [comment]
Получается, что это не баг. а фича) Тогда issue закрываю за ненадобностью.
