### ISSUE TITLE
Ligretto main page inputs font size

### ISSUE THREAD

**Issue by Themezv** [MemeBattle/monorepo#373]
Device: iPhone 14 pro

### Steps:
1. Open ligretto main page
2. Tap on create game or find game inputs
### Current:
Browser zooms to input
### Expected:
Browser don't zoom to input 

Try to set font-size 1rem (16px) to inputs

**Comment by Roman-Prokopchuk** [comment]
Изменил размер шрифта инпутов на `fontSize={{ xs: '1rem' }}` на главной странице. Зум к полю ввода скорее всего возникал только на IOS-устройствах. Они масштабируют страницу, если CSS свойство font-size установлено в значение меньше 16 px. Проверить исправление самостоятельно не смог, так как девтул даже до исправления не имитировал зум для "отзывчивых устройств" на примере встроенного в девтул гугл-хрома айфона 12 про. Надеюсь исправление размера шрифта сработает.
