### ISSUE TITLE
Ligretto. Remove Horizontal scroll on Main Page

### ISSUE THREAD

**Issue by StepanDyubin** [MemeBattle/monorepo#377]
<img width="1728" alt="image" src="https://github.com/MemeBattle/monorepo/assets/22221382/6ef006dc-8314-474d-8b44-5f2833283236">

To reproduce:
1. Open Main page in Chrome.
2. Detach Chrome window (bug reproducing only in detached view)

Expected:
Main page shouldn't have a horizontal scroll 

Note: Probably, horizontal scroll appears only when this is vertical scroll

**Comment by Franqsanz** [comment]
Hello, the problem is that it has a `width: 100vw;` in `<main>` if you remove it the horizontal scroll disappears.
