### ISSUE TITLE
Blog. External links icons

### ISSUE THREAD

**Issue by Themezv** [MemeBattle/monorepo#393]
Current external link:

![Image](https://github.com/MemeBattle/monorepo/assets/12786682/b7f309de-be11-4eff-98c7-64c0911787b5)

Expected:

![Image](https://github.com/MemeBattle/monorepo/assets/12786682/412c9958-2fef-49f4-ab51-36e898dfba69)

figma: https://www.figma.com/file/jsSsetyPx0r5ams0nir2CP/Blog?type=design&node-id=827-306&mode=design&t=7kzuG32qvUKZ2jBo-4

**Comment by margo-yunanova** [comment]
Hi! I'd like to take this issue. It's not clear where to ask TeamLead from [CONTRIBUTING.md](https://github.com/MemeBattle/monorepo/blob/master/CONTRIBUTING.md)

**Comment by Themezv** [comment]
> Hi! I'd like to take this issue. It's not clear where to ask TeamLead from [CONTRIBUTING.md](https://github.com/MemeBattle/monorepo/blob/master/CONTRIBUTING.md)

Yep. Contributing guide isn't clear at the moment :( 
I assigned this issue on you. Also, you can join to our [telegram group](https://t.me/+lvVRxZwYwPRiZDcy) for better communications
